# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  enable:
    # Critical bug detectors
    - govet         # Go vet - reports suspicious constructs
    - staticcheck   # Comprehensive static analysis
    - unused        # Detects unused code
    - ineffassign   # Detects ineffectual assignments
    
    # Security
    - gosec         # Security issues scanner
    
    # Error handling
    - errcheck      # Checks for unchecked errors
    - errorlint     # Error wrapping in Go 1.13+
    
    # Code quality
    - misspell      # Spelling mistakes
    - gocyclo       # Cyclomatic complexity
    - goconst       # Repeated strings that could be constants
